          
Nome: Gerar animação

em:
  # executar automaticamente a cada 12 horas
  Horário:
    - cron: "0 */12 * * *" 
  
  # permite executar manualmente o trabalho a qualquer momento
  workflow_dispatch:
  
  # executar em cada push no branch master
  empurrar:
    Filiais:
    - principal
    
  

Empregos:
  Gerar:
    é executado: ubuntu-mais recente
    Minutos de tempo limite: 10
    
    Passos:
      # gera um jogo de cobra a partir de um gráfico de contribuições de usuários (<github_user_name>) do GitHub, gera uma animação SVG em <svg_out_path>
      - name: Gerar github-contribution-grid-snake.svg
        Usos: Platane/snk/svg-only@v3
        com:
          github_user_name: ${{ github.repository_owner }}
          Saídas: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ segredos. GITHUB_TOKEN }}
          
      # enviar o conteúdo do <build_dir> para uma ramificação
      # O conteúdo estará disponível em https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> ou como página do GitHub
      - name: Envie github-contribution-grid-snake.svg para a ramificação de saída
        Usos: crazy-max/ghaction-github-pages@v2.6.0
        com:
          target_branch: saída
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ segredos. GITHUB_TOKEN }}
